version: '3'
services:
  db:
    image: postgres:11.5
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bboard
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
  angular:
    build: angular
    ports:
      - "4200:4200"
    volumes:
      - ".:/bboard"
    tty: true
volumes:
  bundle:
    driver: local
  postgresql-data:
    driver: local